# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 621a53eafc31262296cb52f6e354a640ca4ab1a1873aba04c6e97d51fd5708d9ef3c46833fedb2cc5177a46570044e8738d86d8c8d87b2b7672a2053638bb1d7

test:
  secret_key_base: e450526f92cb9a139b2d05e486a23a3910227d702557a0caf374d680639810273ac0bd1450b3ddfc5453ff9fdee83b218557b86947c97b97575b64816710a1d5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
